openapi: 3.0.3
info:
  title: Ingredients API
  version: 1.0.0

paths:
  /v1/ingredients:
    get:
      summary: Lister les ingrédients
      tags: [Ingredients]
      parameters:
        - in: query
          name: store_id
          schema: { type: integer }
          description: ID du magasin (optionnel, utilise le magasin du contexte par défaut)
        - in: query
          name: is_allergen
          schema: { type: boolean }
          description: Filtrer par statut d'allergène
        - in: query
          name: is_mandatory
          schema: { type: boolean }
          description: Filtrer par statut obligatoire
        - in: query
          name: is_active
          schema: { type: boolean }
          description: Filtrer par statut d'activation
        - in: query
          name: search
          schema: { type: string }
          description: Recherche par nom
        - in: query
          name: per_page
          schema: { type: integer, default: 25, minimum: 1 }
          description: Nombre d'éléments par page
      responses:
        '200':
          description: Liste paginée des ingrédients
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientPaginatedResponse'
      security:
        - sanctum: []
      x-abilities:
        - ingredient:read
    post:
      summary: Créer un ingrédient
      tags: [Ingredients]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientCreateRequest'
      responses:
        '201':
          description: Ingrédient créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientResponse'
        '422':
          description: Erreur de validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
      security:
        - sanctum: []
      x-abilities:
        - ingredient:create

  /v1/ingredients/{ingredient}:
    parameters:
      - in: path
        name: ingredient
        required: true
        schema: { type: integer }
        description: ID de l'ingrédient
    get:
      summary: Obtenir un ingrédient spécifique
      tags: [Ingredients]
      responses:
        '200':
          description: Détails de l'ingrédient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientResponse'
        '404':
          description: Ingrédient non trouvé
      security:
        - sanctum: []
      x-abilities:
        - ingredient:read
    put:
      summary: Mettre à jour un ingrédient
      tags: [Ingredients]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientUpdateRequest'
      responses:
        '200':
          description: Ingrédient mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientResponse'
        '404':
          description: Ingrédient non trouvé
        '422':
          description: Erreur de validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
      security:
        - sanctum: []
      x-abilities:
        - ingredient:update
    patch:
      summary: Mettre à jour partiellement un ingrédient
      tags: [Ingredients]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientUpdateRequest'
      responses:
        '200':
          description: Ingrédient mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientResponse'
        '404':
          description: Ingrédient non trouvé
        '422':
          description: Erreur de validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
      security:
        - sanctum: []
      x-abilities:
        - ingredient:update
    delete:
      summary: Supprimer un ingrédient
      tags: [Ingredients]
      responses:
        '204':
          description: Ingrédient supprimé
        '404':
          description: Ingrédient non trouvé
      security:
        - sanctum: []
      x-abilities:
        - ingredient:delete

components:
  schemas:
    IngredientCreateRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Steak haché"
        description:
          type: string
          example: "Steak haché de boeuf 100% pur"
        price:
          type: number
          format: float
          example: 2.50
        is_active:
          type: boolean
          default: true
        is_allergen:
          type: boolean
          default: false
        is_mandatory:
          type: boolean
          default: false

    IngredientUpdateRequest:
      type: object
      properties:
        name:
          type: string
          example: "Steak haché"
        description:
          type: string
          example: "Steak haché de boeuf 100% pur"
        price:
          type: number
          format: float
          example: 2.50
        is_active:
          type: boolean
        is_allergen:
          type: boolean
        is_mandatory:
          type: boolean

    IngredientResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Steak haché"
        description:
          type: string
          example: "Steak haché de boeuf 100% pur"
        price:
          type: number
          format: float
          example: 2.50
        is_active:
          type: boolean
          example: true
        is_allergen:
          type: boolean
          example: false
        is_mandatory:
          type: boolean
          example: false
        store_id:
          type: integer
          example: 1
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemSimple'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        main_image:
          type: string
          format: url
          nullable: true

    IngredientPaginatedResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/IngredientResponse'
        meta:
          type: object
          properties:
            current_page:
              type: integer
              example: 1
            per_page:
              type: integer
              example: 25
            total:
              type: integer
              example: 50
            last_page:
              type: integer
              example: 2

    ItemSimple:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Cheeseburger Deluxe"

    ValidationError:
      type: object
      properties:
        message:
          type: string
          example: "Les données fournies ne sont pas valides."
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          example:
            name: ["Le champ nom est obligatoire."]
            price: ["Le prix doit être supérieur à 0."]
